Autonomous (#22)
* added actions and driving for autonomous

* add bool for teleOp in case of autonomous

* Added gradle and MainController headerfile and fixed DriveInterval DriveController by including MainController, Timer and a few weird errors still exist.

* Fixed weird errors.

* Autonomous Changing

* Deleted Autonomous.

* AutoAction

* Readded Auto Folder, found that you can't instantiate an abstract class except as a pointer. Fixed all errors, except weird error in DriveIntervalAction.cpp 'undefined Reference to vtable VARIABLE ...'

* Made routine a pure virtual method and we fixed the method prefixes in DriveIntervalAction. Included MainController.h in DashboardLogger.cpp

* added actions and driving for autonomous

* add bool for teleOp in case of autonomous

* Added gradle and MainController headerfile and fixed DriveInterval DriveController by including MainController, Timer and a few weird errors still exist.

* Fixed weird errors.

* Autonomous Changing

* Deleted Autonomous.

* AutoAction

* Readded Auto Folder, found that you can't instantiate an abstract class except as a pointer. Fixed all errors, except weird error in DriveIntervalAction.cpp 'undefined Reference to vtable VARIABLE ...'

* Made routine a pure virtual method and we fixed the method prefixes in DriveIntervalAction. Included MainController.h in DashboardLogger.cpp

* Fixed weird deconstructewr error by deleting deconstructer

* Added deconstructor to AutoRoutine.* and the whole program compiles.

* restore from backup

* Added files from local backup

* Added DriveForward and DoNothing Routines.

* Fixed AutonomousRoutinePicker by looking at the 2017 Control System wpilib.

* Made runAction a non-pure virtual method.

* Made DoNothing.h inherit public AutoRoutine.

* Deleted build folder.

* Made virtual methods non-pure

* Fixed header files in DriveController

* Deleted WPILib.h include statement

* Deleted circular referencing and renamed MainController.h to Hardware.h, made minute change to Action

* Deleted HeaderFile Hardware.h and replaced it with getter and setter class Hardware

* deleted livewindow getter and setter.

* fixed hardware

* Delete Auto

* init

* WIP fixing AutoPicker.

* WPI Combined AutoBase and AutoRoutine.

* Fixed it somewhow?

* Added shooter controller.

* Just SHoot.cpp header file

* Deleted hardware and replaced it with parameters.

* Added semantic convention.

* Fixed header file in autonomous.

* Non working code. with register auto commented out.

* Initialized autoChooser

* Problem in AutoRoutine and Routines. Virtual Method.

* Fixed parameter order and made prestart virtual. WORKS.

* Changed Ports

* Fixed Polarity of drivecontroller.

* Changed Drive Motors to Sparks.

* Fixed Auto Parameters for Drive.

* clean up

* Fixed Autonomous going into teleop period.

* Fixed WhiteSpace.

* Fixed names

* Reset timer when stopped.

* Added comments

* Fixed weird errors by resetting to earlier commit.

* added boolean to check if auto is started in autoroutinerunner

* Added setup function to reduce code and added false to stop function.

* fixed issues where autonomous couldn't

* Added IsOperatorControl to while loop

* Added IsAutonomous clause.